name: Build Projects

# https://rasterhub.com/fjord/setup-rust-action/src/branch/main/.forgejo/workflows/test.yml
# https://huijzer.xyz/posts/55/installing-forgejo-with-a-separate-runner

on:
  push:
    branches: [master]
#    tags-ignore: ['**']
#  pull_request:
#  workflow_dispatch:

jobs:
  windows-and-linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Update repos and install Rust
        run: |
          sudo apt-get update && sudo apt-get install curl ca-certificates build-essential pkg-config mingw-w64 mingw-w64-common -y
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
          rustup target add x86_64-pc-windows-gnu

      - name: Cache Rust build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            New/kcnet-rust/target
          key: ${{ runner.os }}-rust-${{ hashFiles('New/kcnet-rust/Cargo.lock') }}-${{ hashFiles('New/kcnet-rust/rust-toolchain', 'New/kcnet-rust/rust-toolchain.toml') }}
          restore-keys: |
            ${{ runner.os }}-rust-${{ hashFiles('New/kcnet-rust/Cargo.lock') }}-
            ${{ runner.os }}-rust-

      - name: Build the kcnet-rust project for Linux
        run: |
          cd New/kcnet-rust
          cargo build

      # Well this nearly worked
      # error: error calling dlltool 'x86_64-w64-mingw32-dlltool': No such file or directory (os error 2)
      - name: Build the kcnet-rust project for Windows
        run : |
          cd New/kcnet-rust
          cargo build --target x86_64-pc-windows-gnu

