name: Build Projects

# https://rasterhub.com/fjord/setup-rust-action/src/branch/main/.forgejo/workflows/test.yml
# https://huijzer.xyz/posts/55/installing-forgejo-with-a-separate-runner

on:
  push:
    branches: [master]
#    tags-ignore: ['**']
#  pull_request:
#  workflow_dispatch:

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Update repos and install Rust
        run: |
          sudo apt-get update && sudo apt-get install curl ca-certificates build-essential pkg-config
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source "$HOME/.cargo/env"

      - name: Build the kcnet-rust Rust project
        run: |
          source "$HOME/.cargo/env"
          cd New/kcnet-rust && cargo build

