[package]
name = "kcnet-rust"
version = "0.1.0"
edition = "2024"
description = "KCNet Misc testing with Rust"
authors = ["kelson8"]
license = "MIT"
keywords = ["vector2d", "hashing", "random-numbers"]
#repository = "https://git.kelsoncraft.net/"
# This is mostly a test project, shouldn't be on crates.io just yet.
publish = false

[dependencies]
vector2d = "3.1.1"
rand = "0.10.3"
base64 = "0.23.1"
sha256 = "1.6.0"
digest = "0.11.3"
argon2 = "0.6.0"
password-hash = "0.6.1"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.2", features = ["rt", "rt-multi-thread", "macros"] }

# https://users.rust-lang.org/t/how-to-use-a-rust-rlib-library-in-a-project/113454/9
# Requires my kcnet_lib package in this Git repo.
# I will move things over to this and rename it to kcnet_library_rs later.
kcnet_lib = { path = "../kcnet_lib" }
log = "0.4.34"
# https://www.pistack.xyz/posts/2026-07-27-rust-logging-libraries-env-logger-log4rs-tracing-slog/
#env_logger = "0.11.11"

dotenvy = "0.15"
#simple-logging = "2.0.2"

log4rs = "1"
encryptman = "0.4.0"
hex = "0.4"

aes-gcm = "0.10"
#app-error = "0.2.0"

[features]
# This is somewhat like preprocessors in C++
# https://doc.rust-lang.org/cargo/reference/features.html
# The default feature can be used also
#default = ["debug_test"]

debug_test = []
